name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.2'
          
      - name: Run unit tests
        run: ./scripts/test ./...
